In [3]:
import pandas as pd

In [4]:
metadata = pd.read_csv('movies_metadata.csv', low_memory=False)

In [5]:
metadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [6]:
metadata.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [7]:
metadata = metadata.dropna(subset=['imdb_id','poster_path'])

In [8]:
metadata = metadata.drop(['belongs_to_collection','homepage','popularity','tagline','status'],axis=1)

In [9]:
metadata = metadata.drop(['runtime','release_date','original_language','production_countries','production_companies','spoken_languages','video'],axis=1)

In [10]:
import ast
metadata['genres'] = metadata['genres'].apply(lambda x: ast.literal_eval(x))

In [11]:
metadata['genres'] = metadata['genres'].apply(lambda x: ', '.join([d['name'] for d in x]))

In [12]:
metadata['imdbURL'] = 'https://www.imdb.com/title/' + metadata['imdb_id'] + '/'
metadata['tmdbURL'] = 'https://www.themoviedb.org/movie/' + metadata['id']
metadata['ImageURL'] = 'https://image.tmdb.org/t/p/w92' + metadata['poster_path']

In [13]:
metadata.isnull().sum()

adult               0
budget              0
genres              0
id                  0
imdb_id             0
original_title      0
overview          913
poster_path         0
revenue             3
title               3
vote_average        3
vote_count          3
imdbURL             0
tmdbURL             0
ImageURL            0
dtype: int64

In [14]:
metadata.to_csv('metadata_prep.csv')

In [15]:
metadata.head()

,adult,budget,genres,id,imdb_id,original_title,overview,poster_path,revenue,title,vote_average,vote_count,imdbURL,tmdbURL,ImageURL
0,False,30000000,"Animation, Comedy, Family",862,tt0114709,Toy Story,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,373554033.0,Toy Story,7.7,5415.0,https://www.imdb.com/title/tt0114709/,https://www.themoviedb.org/movie/862,https://image.tmdb.org/t/p/w92/rhIRbceoE9lR4ve...
1,False,65000000,"Adventure, Fantasy, Family",8844,tt0113497,Jumanji,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,262797249.0,Jumanji,6.9,2413.0,https://www.imdb.com/title/tt0113497/,https://www.themoviedb.org/movie/8844,https://image.tmdb.org/t/p/w92/vzmL6fP7aPKNKPR...
2,False,0,"Romance, Comedy",15602,tt0113228,Grumpier Old Men,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,0.0,Grumpier Old Men,6.5,92.0,https://www.imdb.com/title/tt0113228/,https://www.themoviedb.org/movie/15602,https://image.tmdb.org/t/p/w92/6ksm1sjKMFLbO7U...
3,False,16000000,"Comedy, Drama, Romance",31357,tt0114885,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,81452156.0,Waiting to Exhale,6.1,34.0,https://www.imdb.com/title/tt0114885/,https://www.themoviedb.org/movie/31357,https://image.tmdb.org/t/p/w92/16XOMpEaLWkrcPq...
4,False,0,Comedy,11862,tt0113041,Father of the Bride Part II,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,76578911.0,Father of the Bride Part II,5.7,173.0,https://www.imdb.com/title/tt0113041/,https://www.themoviedb.org/movie/11862,https://image.tmdb.org/t/p/w92/e64sOI48hQXyru7...